//! #274 — the ONE display-text clip, on a character boundary.
//!
//! # The bug this replaces
//!
//! There were **four** `clip()` helpers in this crate, with **two different meanings**:
//!
//! | where | body | unit |
//! |---|---|---|
//! | `batt.rs`, `grid.rs` | `s.char_indices().nth(max)` | characters |
//! | `bench.rs`, `rssi.rs` | `&s[..s.len().min(n)]` | **bytes** |
//!
//! Slicing a `&str` at an arbitrary byte index **panics** when that index lands inside a
//! multi-byte character. The two byte-slicing copies carried a comment asserting the input was
//! ASCII ("magical nouns are ASCII, so a byte boundary is a char boundary — never panics"),
//! which made the safety of a panicking operation depend on a property of a *word list in
//! another crate*.
//!
//! That word list is `rust/sigil-names/src/realms.rs`, whose own header says **"Generated by
//! sync-words.sh from words/realms.json — DO NOT EDIT"**. So the thing keeping a fleet board
//! from panicking was that nobody upstream had yet added a word with an accent in it. One
//! `sync-words.sh` run away. `net/names.rs` already knew — its `write_short` carries the note
//! *"the `clip()` helpers in bench.rs/rssi.rs slice bytes and are safe only while the corpus
//! stays ASCII."* A comment that names a hazard is not a guard against it.
//!
//! # Characters, not bytes
//!
//! This clip counts **characters**, matching what `batt.rs`/`grid.rs` already did and what the
//! callers actually want: every caller is fitting text into a fixed-width font on a 128 px
//! panel, where the budget is glyphs. On the all-ASCII corpus of today the two units coincide
//! exactly, so this is a behaviour-preserving change now and a correct one later.
//!
//! Note it is still not a *display-width* clip — a wide or combining character occupies a
//! different number of pixels than one 6x10 cell. Fixing that needs font metrics, not string
//! surgery, and no current input can produce one. Saying so here beats implying otherwise.

/// Clip `s` to at most `max` characters, always on a character boundary. Never panics, for any
/// `&str` and any `max`.
///
/// `max` counts `char`s (Unicode scalar values). `max == 0` yields `""`; a `max` at or beyond
/// the character count yields all of `s`.
pub fn clip(s: &str, max: usize) -> &str {
    match s.char_indices().nth(max) {
        Some((idx, _)) => &s[..idx],
        None => s,
    }
}
