#!/usr/bin/env python3
"""Derive a dependency-node-counting copy of the lunameter harness.

trackermeter measures a DIFFERENT cost than lunameter over the SAME frames, so it
must never keep its own frame list. It generates its `main.rs` from
`tools/lunameter/src/main.rs` on every run and injects two things:

  * a counting `GlobalAlloc`, and
  * one `TRACKER` line per frame, printed between the draw and the PPM dump.

Deriving rather than copying is the point. A second frame list would drift, and a
drifted harness reports on screens the firmware no longer has — which is worse
than no harness, because its numbers still look like numbers. Adding a screen to
lunameter now measures it here too, for free.

Every patch anchor is asserted. If lunameter's harness is restructured this fails
LOUDLY instead of silently measuring a stale copy — the same contract
tools/lunameter/instrument.py holds with the vendored renderer.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "tools" / "lunameter" / "src" / "main.rs"

# ---------------------------------------------------------------------------
# The counting allocator.
# ---------------------------------------------------------------------------
# Slint registers a dependency EVERY time a binding under evaluation reads a
# property (i-slint-core/properties.rs):
#
#   Property::get -> register_as_dependency_to_current_binding
#     -> BindingHolder::register_self_as_dependency
#       -> dep_nodes.push_front(DependencyNode::new(..))   // one raw allocation
#
# There is no dedup — the registration is unconditional — so reading the same
# property twice in one expression allocates twice. The only free read is of a
# property the compiler proved constant: `const_sentinel()` short-circuits the
# registration, which is why literal-derived geometry costs nothing.
#
# The allocation is `SingleLinkedListPinNode<DependencyNode<*const BindingHolder>>`
# = the list node's `next` plus the node's `next`/`prev`/`binding` = four pointers.
# 16 B on riscv32, 32 B on x86_64. The COUNT is architecture-independent, so the
# host can price the device: device bytes = host node count x 16.
PREAMBLE = '''
// ---- trackermeter instrumentation (generated by tools/trackermeter/instrument.py) ----
// NOT part of the firmware, and not part of lunameter either: this file is
// GENERATED from tools/lunameter/src/main.rs. Edit that, never this.
mod trackermeter {
    use std::alloc::{GlobalAlloc, Layout, System};
    use std::sync::atomic::{AtomicI64, Ordering::Relaxed};

    /// Host size of one Slint dependency node (four pointers on x86_64).
    pub const HOST_NODE: usize = 32;
    /// The same node on riscv32, where the watch has to find the bytes.
    pub const DEVICE_NODE: i64 = 16;

    const BUCKET: usize = 8;
    const NB: usize = 65; // 8 B buckets up to 512 B, then a catch-all
    static LIVE_N: [AtomicI64; NB] = [const { AtomicI64::new(0) }; NB];
    static LIVE_BIG: AtomicI64 = AtomicI64::new(0);
    static LIVE_TOTAL: AtomicI64 = AtomicI64::new(0);
    static LIVE_BYTES: AtomicI64 = AtomicI64::new(0);

    #[inline]
    fn note(size: usize, delta: i64) {
        LIVE_TOTAL.fetch_add(delta, Relaxed);
        LIVE_BYTES.fetch_add(delta * size as i64, Relaxed);
        let idx = size / BUCKET;
        if idx < NB {
            LIVE_N[idx].fetch_add(delta, Relaxed);
        } else {
            LIVE_BIG.fetch_add(delta, Relaxed);
        }
    }

    pub struct Counting;

    // Counting only — every request is delegated to the system allocator, so the
    // scene counts lunameter reports from the same run are unaffected.
    unsafe impl GlobalAlloc for Counting {
        unsafe fn alloc(&self, l: Layout) -> *mut u8 {
            let p = unsafe { System.alloc(l) };
            if !p.is_null() { note(l.size(), 1); }
            p
        }
        unsafe fn alloc_zeroed(&self, l: Layout) -> *mut u8 {
            let p = unsafe { System.alloc_zeroed(l) };
            if !p.is_null() { note(l.size(), 1); }
            p
        }
        unsafe fn dealloc(&self, p: *mut u8, l: Layout) {
            note(l.size(), -1);
            unsafe { System.dealloc(p, l) }
        }
        unsafe fn realloc(&self, p: *mut u8, l: Layout, new: usize) -> *mut u8 {
            let np = unsafe { System.realloc(p, l, new) };
            if !np.is_null() { note(l.size(), -1); note(new, 1); }
            np
        }
    }

    /// One line per frame, in lunameter's shape so the two can be pasted together
    /// and diffed the same way.
    ///
    /// `nodes` is the LIVE count for the whole tree at this frame, not a delta:
    /// an absolute number is what a regression check can compare between two runs.
    /// A screen's own cost is the difference against a frame that does not show it
    /// (`aod` is the cheapest such reference in the sweep).
    pub fn report() {
        // Loaded BEFORE the print, because formatting allocates and would
        // otherwise be counted in the numbers it is printing.
        let nodes = LIVE_N[HOST_NODE / BUCKET].load(Relaxed);
        let blocks = LIVE_TOTAL.load(Relaxed);
        let bytes = LIVE_BYTES.load(Relaxed);
        eprintln!(
            "TRACKER nodes={} riscv32_node_bytes={} live_blocks={} \\
             | HOSTsizeof_NOT_DEVICE node={}",
            nodes,
            nodes * DEVICE_NODE,
            blocks,
            HOST_NODE,
        );
        let _ = bytes;
    }
}

#[global_allocator]
static TRACKERMETER_ALLOC: trackermeter::Counting = trackermeter::Counting;
// ---- end trackermeter instrumentation ----
'''

# (anchor, replacement) — each anchor must appear exactly once.
PATCHES = [
    (
        "slint::include_modules!();",
        "slint::include_modules!();\n" + PREAMBLE,
    ),
    # Report between the draw and the PPM dump. Before the dump on purpose: with
    # LUNAMETER_OUT set, dump() writes a 410x502 file, and its buffers must not
    # land in a live-block count.
    (
        """        window.draw_if_needed(|r| {
            r.render_by_line(&mut *sink);
        });
        dump(label, &sink.buf);""",
        """        window.draw_if_needed(|r| {
            r.render_by_line(&mut *sink);
        });
        trackermeter::report();
        dump(label, &sink.buf);""",
    ),
]


def main() -> int:
    if not SRC.is_file():
        print(f"trackermeter: no lunameter harness at {SRC}", file=sys.stderr)
        return 1
    if len(sys.argv) < 2:
        print("trackermeter: usage: instrument.py <dest-src-dir>", file=sys.stderr)
        return 1

    dst = pathlib.Path(sys.argv[1]).resolve()
    text = SRC.read_text()

    for anchor, replacement in PATCHES:
        n = text.count(anchor)
        if n != 1:
            print(
                f"trackermeter: anchor found {n} times, want exactly 1 — "
                f"tools/lunameter/src/main.rs has been restructured and this "
                f"patch must be updated:\n---\n{anchor[:220]}\n---",
                file=sys.stderr,
            )
            return 1
        text = text.replace(anchor, replacement)

    # The generated harness must not be mistaken for a hand-maintained one.
    text = (
        "// GENERATED by tools/trackermeter/instrument.py from\n"
        "// tools/lunameter/src/main.rs — do not edit. Edit the lunameter harness.\n"
        + text
    )

    dst.mkdir(parents=True, exist_ok=True)
    (dst / "main.rs").write_text(text)
    print(f"trackermeter: derived harness at {dst}/main.rs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
