#!/usr/bin/env python3
"""Stage an instrumented copy of the vendored Slint software renderer.

The harness needs three numbers the renderer does not expose: how many
`SceneItem`s, glyph textures and rounded rectangles a frame builds, and how deep
the `SceneBuilder` state stack goes. Rather than keep a second 3.5k-line copy of
the renderer in the repo (which would silently drift from the real one), this
copies `crates/i-slint-renderer-software` into `target/lunameter/renderer-fork`
and applies a few exact-match patches.

Every patch is asserted. If an upstream Slint bump or a local renderer change
moves an anchor, this fails LOUDLY rather than measuring the wrong thing or
quietly measuring an old copy.
"""
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "crates" / "i-slint-renderer-software"
# Destination is supplied by measure.sh, which stages the whole harness OUTSIDE
# the repo (the repo's .cargo/config.toml pins the riscv target for everything
# beneath it, and this is a host build).
DST = (
    pathlib.Path(sys.argv[1]).resolve()
    if len(sys.argv) > 1
    else ROOT / "target" / "lunameter" / "renderer-fork"
)

PREAMBLE = '''
// ---- lunameter instrumentation (generated by tools/lunameter/instrument.py) ----
// NOT part of the firmware. Host-only measurement build.
#[cfg(not(feature = "std"))]
extern crate std as hoststd;
#[cfg(feature = "std")]
use std as hoststd;
pub mod lunameter {
    use core::sync::atomic::{AtomicUsize, Ordering::Relaxed};
    pub static DEPTH: AtomicUsize = AtomicUsize::new(0);
    pub static MAX_DEPTH: AtomicUsize = AtomicUsize::new(0);
    pub fn push() {
        let d = DEPTH.fetch_add(1, Relaxed) + 1;
        MAX_DEPTH.fetch_max(d, Relaxed);
    }
    pub fn pop() {
        DEPTH.fetch_sub(1, Relaxed);
    }
}
// ---- end lunameter instrumentation ----
'''

# (anchor, replacement) — order matters only in that each anchor must be unique.
PATCHES = [
    (
        'extern crate alloc;\n#[cfg(feature = "std")]\nextern crate std;',
        'extern crate alloc;\n#[cfg(feature = "std")]\nextern crate std;\n' + PREAMBLE,
    ),
    (
        """    fn save_state(&mut self) {
        self.state_stack.push(self.current_state);
    }

    fn restore_state(&mut self) {
        self.current_state = self.state_stack.pop().unwrap();
    }""",
        """    fn save_state(&mut self) {
        self.state_stack.push(self.current_state);
        crate::lunameter::push();
    }

    fn restore_state(&mut self) {
        self.current_state = self.state_stack.pop().unwrap();
        crate::lunameter::pop();
    }""",
    ),
    (
        """    Scene::new(
        prepare_scene.processor.items,
        prepare_scene.processor.vectors,
        dirty_region,
        pooled_line_ranges,
    )""",
        """    {
        // The pooled ScenePool keeps capacity across frames, so a screen's
        // RESIDENT cost is the doubling rung its peak count lands on. Element
        // sizes are read with size_of so the 32-bit target's smaller slice
        // pointer is accounted for (SceneTexture is 40 B on x86_64, 28 B on
        // riscv32) — see the README.
        let p = &prepare_scene.processor;
        let rung = |n: usize| -> usize {
            if n == 0 {
                return 0;
            }
            let mut c = 4;
            while c < n {
                c *= 2;
            }
            c
        };
        // The `HOSTsizeof_NOT_DEVICE` group is the HOST's `size_of`, printed only so
        // the rung arithmetic below can be checked. It is NOT the device's: a
        // `SceneTexture` is 40 B here and **28 B on riscv32**, so anyone multiplying
        // a texture count by the host figure over-predicts by 43 %. The
        // `riscv32_rung_bytes` group is the one to read — it already uses 28. The
        // name is deliberately ugly; a plausible-looking `host_sizeof` invited
        // exactly that mistake.
        hoststd::eprintln!(
            "LUNAMETER items={} textures={} rounded={} lingrad={} shared={} max_state_depth={} \
             | HOSTsizeof_NOT_DEVICE item={} texture={} rounded={} state={} \
             | riscv32_rung_bytes items={} tex={} rounded={} sum={}",
            p.items.len(),
            p.vectors.textures.len(),
            p.vectors.rounded_rectangles.len(),
            p.vectors.linear_gradients.len(),
            p.vectors.shared_buffers.len(),
            crate::lunameter::MAX_DEPTH.load(core::sync::atomic::Ordering::Relaxed),
            core::mem::size_of::<SceneItem>(),
            core::mem::size_of::<SceneTexture<'static>>(),
            core::mem::size_of::<RoundedRectangle>(),
            core::mem::size_of::<RenderState>(),
            rung(p.items.len()) * 16,
            rung(p.vectors.textures.len()) * 28,
            rung(p.vectors.rounded_rectangles.len()) * 26,
            rung(p.items.len()) * 16
                + rung(p.vectors.textures.len()) * 28
                + rung(p.vectors.rounded_rectangles.len()) * 26,
        );
    }
    Scene::new(
        prepare_scene.processor.items,
        prepare_scene.processor.vectors,
        dirty_region,
        pooled_line_ranges,
    )""",
    ),
]


def main() -> int:
    if not SRC.is_dir():
        print(f"lunameter: renderer not found at {SRC}", file=sys.stderr)
        return 1
    if DST.exists():
        shutil.rmtree(DST)
    DST.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(SRC, DST)

    lib = DST / "lib.rs"
    text = lib.read_text()
    for anchor, replacement in PATCHES:
        count = text.count(anchor)
        if count != 1:
            print(
                f"lunameter: anchor found {count} times, expected exactly 1.\n"
                f"The vendored renderer changed shape — re-check the patch below "
                f"against crates/i-slint-renderer-software/lib.rs before trusting "
                f"any number this harness prints.\n---\n{anchor[:200]}\n---",
                file=sys.stderr,
            )
            return 1
        text = text.replace(anchor, replacement)
    lib.write_text(text)
    print(f"lunameter: staged instrumented renderer at {DST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
