//! Generated by sync-words.sh from words/realms.json — DO NOT EDIT.
//!
//! Regenerate with `./sync-words.sh --only rust`. Hand-editing a generated corpus is exactly
//! how smol ended up with two copies that drifted from their source with nothing to catch it —
//! the reason this binding exists at all.

use crate::Realm;

/// The `creature` realm — 24 adjectives / 24 nouns.
pub static CREATURE: Realm = Realm {
    name: "creature",
    adjectives: &[
        "Amber",
        "Bashful",
        "Chittering",
        "Curious",
        "Dappled",
        "Downy",
        "Drowsy",
        "Feathered",
        "Furred",
        "Gentle",
        "Glimmering",
        "Hungry",
        "Inquisitive",
        "Lively",
        "Mossy",
        "Nimble",
        "Plucky",
        "Quick",
        "Restless",
        "Scruffy",
        "Skittish",
        "Speckled",
        "Tufted",
        "Whiskered",
    ],
    nouns: &[
        "Sprite",
        "Wisp",
        "Moth",
        "Finch",
        "Wren",
        "Newt",
        "Vole",
        "Hare",
        "Fawn",
        "Cub",
        "Kit",
        "Imp",
        "Pika",
        "Shrew",
        "Marten",
        "Otter",
        "Gecko",
        "Skink",
        "Drake",
        "Wyrmling",
        "Pixie",
        "Brownie",
        "Kelpie",
        "Faun",
    ],
};

/// The `fantasy` realm — 28 adjectives / 25 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static FANTASY: Realm = Realm {
    name: "fantasy",
    adjectives: &[
        "Ancient",
        "Arcane",
        "Blazing",
        "Brimming",
        "Celestial",
        "Draconic",
        "Eldritch",
        "Fabled",
        "Gilded",
        "Hallowed",
        "Hollow",
        "Infernal",
        "Jade",
        "Kindled",
        "Luminous",
        "Lunar",
        "Mystic",
        "Mythic",
        "Noble",
        "Obsidian",
        "Primal",
        "Radiant",
        "Runic",
        "Somber",
        "Spectral",
        "Twilight",
        "Valiant",
        "Woven",
    ],
    nouns: &[
        "Aegis",
        "Beacon",
        "Crown",
        "Dominion",
        "Echo",
        "Ember",
        "Forge",
        "Grimoire",
        "Herald",
        "Hollow",
        "Insignia",
        "Jewel",
        "Keystone",
        "Lantern",
        "Monolith",
        "Nexus",
        "Oracle",
        "Pinnacle",
        "Pulsar",
        "Quartz",
        "Raven",
        "Relic",
        "Sigil",
        "Throne",
        "Warden",
    ],
};

/// The `fleet` realm — 32 adjectives / 32 nouns.
pub static FLEET: Realm = Realm {
    name: "fleet",
    adjectives: &[
        "Ancient",
        "Arcane",
        "Argent",
        "Ashen",
        "Blazing",
        "Brimming",
        "Celestial",
        "Draconic",
        "Eldritch",
        "Fabled",
        "Gilded",
        "Hallowed",
        "Hollow",
        "Infernal",
        "Jade",
        "Kindled",
        "Luminous",
        "Lunar",
        "Mystic",
        "Mythic",
        "Noble",
        "Obsidian",
        "Primal",
        "Radiant",
        "Runic",
        "Seraphic",
        "Somber",
        "Spectral",
        "Twilight",
        "Umbral",
        "Valiant",
        "Woven",
    ],
    nouns: &[
        "Aegis",
        "Bastion",
        "Brazier",
        "Cairn",
        "Chalice",
        "Citadel",
        "Diadem",
        "Dominion",
        "Echo",
        "Ember",
        "Glyph",
        "Grimoire",
        "Insignia",
        "Jewel",
        "Keystone",
        "Lantern",
        "Lodestar",
        "Monolith",
        "Nexus",
        "Obelisk",
        "Orrery",
        "Pinnacle",
        "Pulsar",
        "Quartz",
        "Raven",
        "Relic",
        "Sanctum",
        "Spire",
        "Talisman",
        "Throne",
        "Vigil",
        "Warden",
    ],
};

/// The `forge` realm — 14 adjectives / 14 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static FORGE: Realm = Realm {
    name: "forge",
    adjectives: &[
        "Molten",
        "Hammered",
        "Tempered",
        "Forged",
        "Glowing",
        "Smoldering",
        "Sparking",
        "Kilned",
        "Ironclad",
        "Wrought",
        "Bellowed",
        "Anvilled",
        "White-Hot",
        "Smelted",
    ],
    nouns: &[
        "Forge",
        "Anvil",
        "Kiln",
        "Quench",
        "Hammer",
        "Smithy",
        "Smelter",
        "Ironheart",
        "Wright",
        "Crucible",
        "Bellows",
        "Mold",
        "Ingot",
        "Foundry",
    ],
};

/// The `oracle` realm — 14 adjectives / 14 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static ORACLE: Realm = Realm {
    name: "oracle",
    adjectives: &[
        "Augural",
        "Fated",
        "Prescient",
        "Sibylline",
        "Dreaming",
        "Prophetic",
        "Foretold",
        "Whispered",
        "Veiled",
        "Divining",
        "Foreseen",
        "Omened",
        "Occult",
        "Scrying",
    ],
    nouns: &[
        "Oracle",
        "Augur",
        "Sibyl",
        "Prophet",
        "Omen",
        "Vision",
        "Harbinger",
        "Dreamer",
        "Seer",
        "Scrying",
        "Prophecy",
        "Runecast",
        "Soothsayer",
        "Divination",
    ],
};

/// The `signal` realm — 30 adjectives / 30 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static SIGNAL: Realm = Realm {
    name: "signal",
    adjectives: &[
        "Amplified",
        "Beaconing",
        "Blinking",
        "Broadcast",
        "Broadcasting",
        "Channeled",
        "Channelled",
        "Decoded",
        "Echoing",
        "Encrypted",
        "Filtered",
        "Grounded",
        "Harmonic",
        "Humming",
        "Isolated",
        "Jittered",
        "Keyed",
        "Latched",
        "Looping",
        "Modulated",
        "Narrowed",
        "Oscillating",
        "Pulsed",
        "Pulsing",
        "Quantized",
        "Relayed",
        "Resonant",
        "Synced",
        "Syncing",
        "Tuned",
    ],
    nouns: &[
        "Antenna",
        "Beacon",
        "Broadcast",
        "Carrier",
        "Channel",
        "Diode",
        "Emitter",
        "Frequency",
        "Gate",
        "Harbor",
        "Harmonic",
        "Impulse",
        "Junction",
        "Keystone",
        "Lattice",
        "Lighthouse",
        "Link",
        "Modem",
        "Node",
        "Oscillator",
        "Packet",
        "Ping",
        "Pulsar",
        "Pulse",
        "Qubit",
        "Relay",
        "Semaphore",
        "Signal",
        "Telegraph",
        "Transponder",
    ],
};

/// The `stellar` realm — 14 adjectives / 14 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static STELLAR: Realm = Realm {
    name: "stellar",
    adjectives: &[
        "Stellar",
        "Nebular",
        "Orbital",
        "Cosmic",
        "Gleaming",
        "Supernal",
        "Luminous",
        "Twinkling",
        "Celestial",
        "Gravitational",
        "Eclipsed",
        "Comet-Borne",
        "Equinoctial",
        "Far-Flung",
    ],
    nouns: &[
        "Nova",
        "Quasar",
        "Nebula",
        "Comet",
        "Orbit",
        "Solstice",
        "Zenith",
        "Meridian",
        "Constellation",
        "Supernova",
        "Parallax",
        "Lensing",
        "Perihelion",
        "Eclipse",
    ],
};

/// The `tarot` realm — 14 adjectives / 14 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static TAROT: Realm = Realm {
    name: "tarot",
    adjectives: &[
        "Arcane",
        "Suspended",
        "Towering",
        "Fated",
        "Foolish",
        "Judged",
        "Hierophantic",
        "Crowned",
        "Reversed",
        "Illumined",
        "Querent",
        "Esoteric",
        "Hermetic",
        "Drawn",
    ],
    nouns: &[
        "Arcana",
        "Fool",
        "Hierophant",
        "Hanged",
        "Tower",
        "Star",
        "Sun",
        "Moon",
        "Judgement",
        "World",
        "Wheel",
        "Chariot",
        "Hermit",
        "Magician",
    ],
};

/// The `void` realm — 14 adjectives / 14 nouns.
///
/// Gated: this realm names a **build**, not a thing. Its words currently agree with the
/// go/python/js embeds, but that agreement is a maintained property rather than a structural
/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a
/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the
/// feature, so a default build carries none of these words in `.rodata`, which matters to the
/// firmware consumers this binding exists for.
#[cfg(feature = "divergent-themed-realms")]
pub static VOID: Realm = Realm {
    name: "void",
    adjectives: &[
        "Hushed",
        "Unmade",
        "Vacant",
        "Silent",
        "Drifting",
        "Eclipsing",
        "Lost",
        "Shrouded",
        "Fading",
        "Hollowed",
        "Absent",
        "Devoured",
        "Untold",
        "Dimming",
    ],
    nouns: &[
        "Abyss",
        "Hollow",
        "Eclipse",
        "Drift",
        "Hush",
        "Shroud",
        "Silence",
        "Chasm",
        "Umbra",
        "Threshold",
        "Rift",
        "Cipher",
        "Vanishment",
        "Absence",
    ],
};

/// EVERY realm, sorted by name — the identity realms plus the themed, build-provenance
/// ones. Reachable only with `divergent-themed-realms`; the default list below is the
/// identity subset.
#[cfg(feature = "divergent-themed-realms")]
pub static REALMS: &[&Realm] = &[
    &CREATURE,
    &FANTASY,
    &FLEET,
    &FORGE,
    &ORACLE,
    &SIGNAL,
    &STELLAR,
    &TAROT,
    &VOID,
];

/// Without `divergent-themed-realms`, only the IDENTITY realms are handed out — the ones
/// naming a *thing* (a board, a familiar) rather than a *build*. A themed realm reached
/// from here would be a version name acquired without the Cargo.toml declaration that
/// makes the hazard visible to a reviewer, which is the entire point of the gate.
///
/// ⚠️ NOT "realms that exist in no other binding". That was the criterion until
/// 2026-07-29, when `--all` wrote `fleet` and `creature` into go/python/js — every realm
/// now exists in all four bindings, so these two can diverge like any other. What keeps
/// them default is what they NAME; the derived content check below still gates them if
/// their words drift from the Go embed.
#[cfg(not(feature = "divergent-themed-realms"))]
pub static REALMS: &[&Realm] = &[
    &CREATURE,
    &FLEET,
];

/// Look up a realm by name, falling back to `fantasy` for an unknown one — matching Go's
/// `GenerateName`, which falls back rather than erroring.
///
/// ⚠️ Only available with `divergent-themed-realms`. A name-based lookup is exactly how a
/// mixed-language project would silently acquire a divergent version name — it asks for
/// "fantasy" in two languages and gets two different answers. Without the feature no themed
/// realm is reachable at all — not through this function and not through `REALMS` — so the
/// mistake is unrepresentable rather than documented. Use [`FLEET`](crate::FLEET) directly
/// for node identity.
#[cfg(feature = "divergent-themed-realms")]
pub const fn realm_by_name(name: &str) -> &'static Realm {
    let mut i = 0;
    while i < REALMS.len() {
        if crate::str_eq_ascii_ci(REALMS[i].name, name) {
            return REALMS[i];
        }
        i += 1;
    }
    &FANTASY
}
