//! Generated by sync-words.sh from words/reserved.json — DO NOT EDIT.
//!
//! Words that must never name a node, because each already names something else: a mesh ROLE
//! (`crown` IS the gateway role), a wire FRAME, a FEATURE, or a sibling PROJECT. An identity
//! drawn from the same vocabulary as a role is a permanent ambiguity — a board called Crown
//! that is not the crown reads as a contradiction in every log line and dashboard.
//!
//! Source of truth: lexicon.realm.watch/vocabularies/reserved.yaml, which groups these by
//! reason. Consumers only need membership, so this is a flat sorted list.

/// The reserved words — lower-case, sorted.
pub static RESERVED: &[&str] = &[
    "ack",
    "bard",
    "batt",
    "beacon",
    "bench",
    "cast",
    "cfg",
    "clock",
    "crown",
    "custom",
    "diag",
    "fam",
    "familiar",
    "forge",
    "gateway",
    "grid",
    "hello",
    "herald",
    "holder",
    "leaf",
    "ledger",
    "lexicon",
    "meshscope",
    "observatory",
    "oracle",
    "peer",
    "realm",
    "relay",
    "scan",
    "scribe",
    "sigil",
    "snake",
    "snk",
    "time",
];
